services:
  api:
    build: .
    image: be-wwg-aws-mailbridge-api:1.1
    container_name: mailBridge_service
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - api_network

networks:
  api_network:
    driver: bridge